# -*- coding: utf-8 -*-
"""内置工作流模板（种子数据，参照 MaxKB default_workflow.json 的做法按本项目节点 schema 重写）。

服务首次启动时由 workflow_service.seed_builtin_templates() 幂等写入 tb_workflow_template。
"""
from __future__ import annotations

BUILTIN_TEMPLATES: list[dict] = [
    {
        "name": "基础问答（输入→LLM→输出）",
        "description": "最简工作流：用户提问直接交给大模型回答",
        "category": "CONVERSATION",
        "icon": "MessageOutlined",
        "graph": {
            "nodes": [
                {"id": "start_1", "type": "START", "label": "开始",
                 "position": {"x": 100, "y": 200},
                 "data": {"fields": [
                     {"name": "query", "label": "用户问题", "type": "PARAGRAPH", "required": True},
                 ]}},
                {"id": "llm_1", "type": "LLM", "label": "大模型",
                 "position": {"x": 350, "y": 200},
                 "data": {"modelId": None, "systemPrompt": "你是一个乐于助人的AI助手。",
                          "promptTemplate": "{{start_1.query}}", "streaming": True,
                          "outputVariable": "output"}},
                {"id": "end_1", "type": "END", "label": "结束",
                 "position": {"x": 600, "y": 200},
                 "data": {"outputs": [{"name": "answer", "value": "{{llm_1.output}}"}],
                          "outputMode": "TEMPLATE", "streaming": True}},
            ],
            "edges": [
                {"id": "e1", "source": "start_1", "sourceHandle": "output",
                 "target": "llm_1", "targetHandle": "input"},
                {"id": "e2", "source": "llm_1", "sourceHandle": "output",
                 "target": "end_1", "targetHandle": "input"},
            ],
        },
    },
    {
        "name": "知识库问答（RAG）",
        "description": "检索知识库后由大模型基于检索内容回答",
        "category": "RAG",
        "icon": "DatabaseOutlined",
        "graph": {
            "nodes": [
                {"id": "start_1", "type": "START", "label": "开始",
                 "position": {"x": 80, "y": 220},
                 "data": {"fields": [
                     {"name": "query", "label": "用户问题", "type": "PARAGRAPH", "required": True},
                 ]}},
                {"id": "kb_1", "type": "KNOWLEDGE_RETRIEVAL", "label": "知识检索",
                 "position": {"x": 320, "y": 220},
                 "data": {"knowledgeBaseIds": [], "queryVariable": "{{start_1.query}}",
                          "topK": 5, "scoreThreshold": 0.5, "retrievalMode": "VECTOR",
                          "outputVariable": "documents"}},
                {"id": "llm_1", "type": "LLM", "label": "大模型",
                 "position": {"x": 560, "y": 220},
                 "data": {"modelId": None,
                          "systemPrompt": "请仅根据以下参考资料回答用户问题，资料中没有相关信息时如实说明。",
                          "promptTemplate": "参考资料：\n{{kb_1.text}}\n\n用户问题：{{start_1.query}}",
                          "streaming": True}},
                {"id": "end_1", "type": "END", "label": "结束",
                 "position": {"x": 800, "y": 220},
                 "data": {"outputs": [{"name": "answer", "value": "{{llm_1.output}}"}],
                          "outputMode": "TEMPLATE"}},
            ],
            "edges": [
                {"id": "e1", "source": "start_1", "sourceHandle": "output",
                 "target": "kb_1", "targetHandle": "input"},
                {"id": "e2", "source": "kb_1", "sourceHandle": "output",
                 "target": "llm_1", "targetHandle": "input"},
                {"id": "e3", "source": "llm_1", "sourceHandle": "output",
                 "target": "end_1", "targetHandle": "input"},
            ],
        },
    },
    {
        "name": "问题分类路由",
        "description": "问题分类器将不同类型的问题路由到不同处理分支",
        "category": "CONVERSATION",
        "icon": "BranchesOutlined",
        "graph": {
            "nodes": [
                {"id": "start_1", "type": "START", "label": "开始",
                 "position": {"x": 80, "y": 260},
                 "data": {"fields": [
                     {"name": "query", "label": "用户问题", "type": "PARAGRAPH", "required": True},
                 ]}},
                {"id": "cls_1", "type": "QUESTION_CLASSIFIER", "label": "问题分类",
                 "position": {"x": 320, "y": 260},
                 "data": {"modelId": None, "inputVariable": "{{start_1.query}}",
                          "categories": [
                              {"id": "tech", "name": "技术问题", "description": "编程、系统、架构相关"},
                              {"id": "biz", "name": "业务问题", "description": "业务咨询、流程相关"},
                          ]}},
                {"id": "llm_tech", "type": "LLM", "label": "技术解答",
                 "position": {"x": 580, "y": 160},
                 "data": {"modelId": None, "systemPrompt": "你是资深技术专家，回答简洁准确。",
                          "promptTemplate": "{{start_1.query}}", "streaming": True}},
                {"id": "llm_biz", "type": "LLM", "label": "业务解答",
                 "position": {"x": 580, "y": 360},
                 "data": {"modelId": None, "systemPrompt": "你是业务咨询顾问，回答热情周到。",
                          "promptTemplate": "{{start_1.query}}", "streaming": True}},
                {"id": "end_1", "type": "END", "label": "结束",
                 "position": {"x": 840, "y": 260},
                 "data": {"outputs": [{"name": "answer", "value": ""}], "outputMode": "TEMPLATE"}},
            ],
            "edges": [
                {"id": "e1", "source": "start_1", "sourceHandle": "output",
                 "target": "cls_1", "targetHandle": "input"},
                {"id": "e2", "source": "cls_1", "sourceHandle": "branch:tech",
                 "target": "llm_tech", "targetHandle": "input"},
                {"id": "e3", "source": "cls_1", "sourceHandle": "branch:biz",
                 "target": "llm_biz", "targetHandle": "input"},
                {"id": "e4", "source": "llm_tech", "sourceHandle": "output",
                 "target": "end_1", "targetHandle": "input"},
                {"id": "e5", "source": "llm_biz", "sourceHandle": "output",
                 "target": "end_1", "targetHandle": "input"},
            ],
        },
    },
    {
        "name": "参数提取（自然语言→结构化）",
        "description": "从自然语言中提取结构化参数",
        "category": "EXTRACTION",
        "icon": "FilterOutlined",
        "graph": {
            "nodes": [
                {"id": "start_1", "type": "START", "label": "开始",
                 "position": {"x": 100, "y": 200},
                 "data": {"fields": [
                     {"name": "text", "label": "原始文本", "type": "PARAGRAPH", "required": True},
                 ]}},
                {"id": "pe_1", "type": "PARAMETER_EXTRACTOR", "label": "参数提取",
                 "position": {"x": 360, "y": 200},
                 "data": {"modelId": None, "inputVariable": "{{start_1.text}}",
                          "parameters": [
                              {"name": "name", "type": "string", "description": "人名", "required": True},
                              {"name": "date", "type": "string", "description": "日期"},
                          ]}},
                {"id": "end_1", "type": "END", "label": "结束",
                 "position": {"x": 620, "y": 200},
                 "data": {"outputs": [
                     {"name": "name", "value": "{{pe_1.name}}"},
                     {"name": "date", "value": "{{pe_1.date}}"},
                 ], "outputMode": "JSON"}},
            ],
            "edges": [
                {"id": "e1", "source": "start_1", "sourceHandle": "output",
                 "target": "pe_1", "targetHandle": "input"},
                {"id": "e2", "source": "pe_1", "sourceHandle": "output",
                 "target": "end_1", "targetHandle": "input"},
            ],
        },
    },
    {
        "name": "文本生成（模板+代码）",
        "description": "代码处理数据 + 模板渲染生成报告",
        "category": "GENERATION",
        "icon": "FileTextOutlined",
        "graph": {
            "nodes": [
                {"id": "start_1", "type": "START", "label": "开始",
                 "position": {"x": 80, "y": 200},
                 "data": {"fields": [
                     {"name": "title", "label": "标题", "type": "SHORT_TEXT", "required": True},
                     {"name": "items", "label": "要点（逗号分隔）", "type": "PARAGRAPH"},
                 ]}},
                {"id": "code_1", "type": "CODE", "label": "解析要点",
                 "position": {"x": 330, "y": 200},
                 "data": {"language": "PYTHON",
                          "code": "def main(**kwargs):\n    items = kwargs.get('items') or ''\n    return {'items': [i.strip() for i in items.split(',') if i.strip()]}",
                          "inputs": [{"name": "items", "sourceVariable": "{{start_1.items}}"}]}},
                {"id": "tpl_1", "type": "TEMPLATE", "label": "渲染报告",
                 "position": {"x": 580, "y": 200},
                 "data": {"engine": "SIMPLE",
                          "template": "# {{start_1.title}}\n{% for item in items %}\n- {{item}}\n{% endfor %}",
                          "variables": [{"name": "items", "reference": "{{code_1.items}}"}]}},
                {"id": "end_1", "type": "END", "label": "结束",
                 "position": {"x": 820, "y": 200},
                 "data": {"outputs": [{"name": "report", "value": "{{tpl_1.output}}"}],
                          "outputMode": "TEMPLATE"}},
            ],
            "edges": [
                {"id": "e1", "source": "start_1", "sourceHandle": "output",
                 "target": "code_1", "targetHandle": "input"},
                {"id": "e2", "source": "code_1", "sourceHandle": "output",
                 "target": "tpl_1", "targetHandle": "input"},
                {"id": "e3", "source": "tpl_1", "sourceHandle": "output",
                 "target": "end_1", "targetHandle": "input"},
            ],
        },
    },
]
